/* ============================================================
   AUTO-GENERATED by scripts/build-notes.js — do not edit by hand.
   Drop a folder of numbered JPEG pages (1.jpg, 2.jpg, ...) into
   assets/notes/ and commit; the pre-commit hook regenerates this
   file and the thumbnail image for you.
   ============================================================ */

const NOTES = [
  {
    "slug": "incomplete-gears-power-transmission",
    "title": "[Incomplete] Gears + Power Transmission",
    "thumb": "assets/notes/thumbs/incomplete-gears-power-transmission.jpg",
    "images": [
      "assets/notes/incomplete-gears-power-transmission/1.jpg",
      "assets/notes/incomplete-gears-power-transmission/2.jpg",
      "assets/notes/incomplete-gears-power-transmission/3.jpg"
    ],
    "pages": 3,
    "added": "2026-08-05"
  }
];
