/* ============================================================
   AUTO-GENERATED by scripts/build-notes.js — do not edit by hand.
   Drop a folder of numbered JPEG pages (1.jpg, 2.jpg, ...) into
   assets/notes/ and commit; the pre-commit hook regenerates this
   file and the thumbnail image for you.
   ============================================================ */

const NOTES = [
  {
    "slug": "gears-power-transmission",
    "title": "Gears + Power Transmission",
    "thumb": "assets/notes/thumbs/gears-power-transmission.jpg",
    "images": [
      "assets/notes/gears-power-transmission/1.jpg",
      "assets/notes/gears-power-transmission/2.jpg",
      "assets/notes/gears-power-transmission/3.jpg",
      "assets/notes/gears-power-transmission/4.jpg",
      "assets/notes/gears-power-transmission/5.jpg"
    ],
    "pages": 5,
    "added": "2026-08-06"
  }
];
