/* ============================================================
   AUTO-GENERATED by scripts/build-notes.js — do not edit by hand.
   Drop a PDF into assets/notes/ and commit; the pre-commit hook
   regenerates this file and the first-page thumbnail for you.
   ============================================================ */

const NOTES = [
  {
    "slug": "incomplete-gears-power-transmission",
    "title": "[Incomplete] Gears + Power Transmission",
    "file": "assets/notes/[Incomplete] Gears + Power Transmission.pdf",
    "thumb": "assets/notes/thumbs/incomplete-gears-power-transmission.jpg",
    "pages": 3,
    "size": "18 MB",
    "added": "2026-08-05"
  }
];
