/* ============================================================
   Scans assets/notes/ for PDFs and generates:
     - a first-page thumbnail per PDF, in assets/notes/thumbs/
     - js/notes-data.js, the data file notes.html renders from

   Run manually with `npm run build:notes`, or automatically via
   the .githooks/pre-commit hook whenever a commit touches
   assets/notes/ — the hook stages the results into that commit.

   Uses macOS's built-in `sips` (already relied on by
   scripts/build-pdf.js) plus poppler's `pdftoppm`/`pdfinfo`
   (already installed — same tools used throughout this project's
   PDF tooling) instead of adding npm dependencies.
   ============================================================ */

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const NOTES_DIR = path.join(ROOT, "assets", "notes");
const THUMB_DIR = path.join(NOTES_DIR, "thumbs");
const OUT_DATA = path.join(ROOT, "js", "notes-data.js");

fs.mkdirSync(THUMB_DIR, { recursive: true });

function slugify(name) {
  return name
    .replace(/\.pdf$/i, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function titleize(name) {
  return name
    .replace(/\.pdf$/i, "")
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function pageCount(pdfPath) {
  try {
    const out = execFileSync("pdfinfo", [pdfPath], { encoding: "utf8" });
    const m = out.match(/Pages:\s+(\d+)/);
    return m ? parseInt(m[1], 10) : null;
  } catch {
    return null;
  }
}

function humanSize(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let n = bytes / 1024, i = 0;
  while (n >= 1024 && i < units.length - 1) { n /= 1024; i++; }
  return `${n.toFixed(n < 10 ? 1 : 0)} ${units[i]}`;
}

const pdfFiles = fs.readdirSync(NOTES_DIR).filter((f) => f.toLowerCase().endsWith(".pdf"));

const notes = pdfFiles.map((originalName) => {
  const slug = slugify(originalName);
  const title = titleize(originalName);

  // Serve every note under a slugified filename, no matter what it was
  // dropped in as. Vercel's router reserves [bracket] syntax for dynamic
  // routes even on plain static files, so a name like "[Incomplete] Notes.pdf"
  // 404s once deployed — square brackets, spaces, and other punctuation
  // are all safest to just not have in a served path. The original
  // filename still drives the human-readable title above.
  const safeName = `${slug}.pdf`;
  let src = path.join(NOTES_DIR, originalName);
  if (originalName !== safeName) {
    const safeSrc = path.join(NOTES_DIR, safeName);
    fs.renameSync(src, safeSrc);
    src = safeSrc;
    console.log(`renamed "${originalName}" -> "${safeName}" (URL-safe for deployment)`);
  }

  const stat = fs.statSync(src);
  const thumbName = `${slug}.jpg`;
  const thumbPath = path.join(THUMB_DIR, thumbName);

  // (re)build the thumbnail only if it's missing or stale
  if (!fs.existsSync(thumbPath) || fs.statSync(thumbPath).mtimeMs < stat.mtimeMs) {
    const tmpPng = path.join(THUMB_DIR, `.tmp-${slug}.png`);
    execFileSync("pdftoppm", [
      "-png", "-singlefile",
      "-r", "150",
      "-f", "1", "-l", "1",
      src,
      tmpPng.replace(/\.png$/, ""),
    ], { stdio: "pipe" });
    execFileSync("sips", [
      "-s", "format", "jpeg",
      "-s", "formatOptions", "82",
      "-Z", "900",
      tmpPng,
      "--out", thumbPath,
    ], { stdio: "pipe" });
    fs.unlinkSync(tmpPng);
  }

  return {
    slug,
    title,
    file: `assets/notes/${safeName}`,
    thumb: `assets/notes/thumbs/${thumbName}`,
    pages: pageCount(src),
    size: humanSize(stat.size),
    added: stat.mtime.toISOString().slice(0, 10),
  };
});

notes.sort((a, b) => b.added.localeCompare(a.added) || a.title.localeCompare(b.title));

// clean up thumbnails for PDFs that no longer exist
const keep = new Set(notes.map((n) => path.basename(n.thumb)));
for (const f of fs.readdirSync(THUMB_DIR)) {
  if (f.endsWith(".jpg") && !keep.has(f)) fs.unlinkSync(path.join(THUMB_DIR, f));
}

const banner = `/* ============================================================
   AUTO-GENERATED by scripts/build-notes.js — do not edit by hand.
   Drop a PDF into assets/notes/ and commit; the pre-commit hook
   regenerates this file and the first-page thumbnail for you.
   ============================================================ */\n\n`;

fs.writeFileSync(OUT_DATA, banner + `const NOTES = ${JSON.stringify(notes, null, 2)};\n`);

console.log(`Notes data built → js/notes-data.js (${notes.length} note${notes.length === 1 ? "" : "s"})`);
